// sandbox/io23-demo/SolidJS/src/components/AutoCompleteSync.tsx
'use client';

import Fuse from "fuse.js";
import { Accessor, For, Show, createMemo, createResource } from 'solid-js';
import { SailData } from "~/common/getSailData";
import createSearchTasks, { SearchResult } from "~/common/createSearchTasks";
import filterResultsSync from "~/common/filterResultsSync";
import SailboatResults from "~/common/components/SailboatResults";
import SailboatPreview from "~/common/components/SailboatPreview";

export default function AutoCompleteSync({ searchTerm, sailData }: { searchTerm: Accessor<string>, sailData: SailData }) {
	const [searchers] = createResource(() => createSearchTasks(Fuse, sailData));
	const results =  createMemo(() => filterResultsSync(searchers()!, searchTerm()));
	const slicedResults = () => results()?.slice(0, 10);

	return (
		<Show when={results().length > 0}>
			<SailboatResults results={results()!}></SailboatResults>
			<For each={slicedResults()}>{(result: SearchResult) =>
				<SailboatPreview result={result}></SailboatPreview>
			}</For>
		</Show>
	);
};

// sandbox/io23-demo/NextJS/src/components/AutoCompleteSync.tsx
'use client';

import Fuse from "fuse.js";
import { useMemo } from "react";
import { SailData } from "@/common/getSailData";
import createSearchTasks, { SearchResult } from "@/common/createSearchTasks";
import filterResultsSync from "@/common/filterResultsSync";
import SailboatResults from "@/common/components/SailboatResults";
import SailboatPreview from "@/common/components/SailboatPreview";

export default function AutoComplete({ searchTerm, sailData }: { searchTerm: string, sailData: SailData }) {
	const searchers = useMemo(() => createSearchTasks(Fuse, sailData), [sailData]);
	const results = useMemo(() => filterResultsSync(searchers, searchTerm), [searchers, searchTerm]);
	const slicedResults = results.slice(0, 10);

	if (results.length == 0) {
		return <></>;
	}

	return (
		<>
			<SailboatResults results={results}></SailboatResults>
			{ slicedResults.map((result: SearchResult) =>
				<SailboatPreview key={result.item.id} result={result}></SailboatPreview>
			)}
		</>
	);
};
