// sandbox/io23-demo/SolidJS/src/hooks/utils/useAbortSignallingTransition.tsx
import { Accessor, createSignal } from "solid-js";
import useAwaitableTransition from "./useAwaitableTransition";

export default function useAbortSignallingTransition() : [Accessor<boolean>, (fn: () => void) => Promise<void>, Accessor<AbortSignal>] {
	const [isPending, startAwaitableTransition] = useAwaitableTransition();
	const [abortController, setAbortController] = createSignal(new AbortController);
  
	  const startAbortSignallingTransition = async (callback: () => void) => {
		  const newAbortController = new AbortController();
  
		  try {
			  await startAwaitableTransition(() => {
				  callback();
				  setAbortController(newAbortController);
			  });
		  } catch (ex) {
			  newAbortController.abort();
			  throw ex;
		  }
	}
  
	  return [isPending, startAbortSignallingTransition, () => abortController().signal];
  }

// sandbox/react-flushSync/hooks/useAbortSignallingTransition.js
import { useCallback, useRef } from "react";
import useAwaitableTransition from "./useAwaitableTransition";

export default function useAbortSignallingTransition() {
	const [isPending, startAwaitableTransition] = useAwaitableTransition();
	const abortController = useRef();

	const startAbortSignallingTransition = useCallback(async (callback) => {
		abortController.current = new AbortController;

		try {
			await startAwaitableTransition(callback);
		} catch(ex) {
			abortController.current.abort();
			// throw ex;
		}
	}, [startAwaitableTransition]);

	return [isPending, startAbortSignallingTransition, abortController.signal];
};
