// sandbox/io23-demo/SolidJS/src/hooks/utils/useAwaitableTransition.tsx
import { Accessor, createEffect, createRenderEffect, useTransition } from "solid-js";

export default function useAwaitableTransition() : [Accessor<boolean>, (fn: () => void) => Promise<void>] {
	const [isPending, startTransition] = useTransition();
	let resolveRef: (((value?: any) => void) | undefined);
	let rejectRef: (((reason?: any) => void) | undefined);

	const startAwaitableTransition = async (callback: () => void): Promise<void> => {
		rejectRef?.();

		return new Promise((resolve, reject) => {
			resolveRef = resolve;
			rejectRef = reject;

			startTransition(() => {
				callback();
			});
		});
	};
	
	// TODO: Try render effect?
	createRenderEffect(() => {
		if (!isPending()) {
			resolveRef?.();

			resolveRef = undefined;
			rejectRef = undefined;
		}
	});

	return [isPending, startAwaitableTransition];
}

// sandbox/react-flushSync/hooks/useAwaitableTransition.js
import { useCallback, useRef, useTransition } from "react";

export default function useAwaitableTransition() {
	const [isPending, startTransition] = useTransition();
	const resolveRef = useRef();
	const rejectRef = useRef();

	const startAwaitableTransition = useCallback(
		(callback) => {
			// Starting new transitions will cancel previous ones, so reject() the previous promise
			rejectRef.current?.();

			return new Promise((resolve, reject) => {
				resolveRef.current = resolve;
				rejectRef.current = reject;
				startTransition(callback);
			});
		}, [startTransition, rejectRef]);

	if (!isPending && resolveRef.current) {
		resolveRef.current?.();

		resolveRef.current = undefined;
		rejectRef.current = undefined;
	}

	return [isPending, startAwaitableTransition];
};
