// sandbox/io23-demo/SolidJS/src/hooks/useDebouncedEffect.tsx
import { Accessor, createEffect, onCleanup } from "solid-js";

// This is a very trivial version of this hook.
// There are several libraries that provide more robust versions.
export default function useDefferredEffect<T>(deps: Accessor<T>, callback: (val: T) => void, delay: number) {
	// TODO: perhaps using the promise based version of setTimeout and createResource() is better
	createEffect(() => {
		const val = deps();
		const timerid = setTimeout(() => callback(val), delay);
		onCleanup(() => {
			clearTimeout(timerid);
		});
	});
  };

// sandbox/react-flushSync/hooks/useDebouncedEffect.js
import { useEffect } from "react";

// This is a very trivial version of this hook.
// There are several libraries that provide more robust versions.
export default function useDebouncedEffect(callback, delay, deps) {
	useEffect(() => {
		const timerid = setTimeout(callback, delay);
		return () => clearTimeout(timerid);
	}, deps); // eslint-disable-line react-hooks/exhaustive-deps
}
