// sandbox/io23-demo/React/src/components/WebVitalsMonitor.tsx
'use client';

import measureInteractions from "../common/measureInteractions.js"
import measureLoAF from "../common/measureLoAF.js";

import { useEffect } from "react";

// This could be a hook, but its a component in case we ever inject UI.
export default function WebVitalsMonitor() {
	useEffect(() => {
		// console.log('Recording Interaction to Next Paint (INP).');

		const observers = [
			measureInteractions(),
			measureLoAF(),
		];
		return () => observers.forEach(observer => observer?.disconnect());
	}, []);

	return <></>;
}

// sandbox/io23-demo/SolidJS/src/components/WebVitalsMonitor.tsx
import { createEffect, onCleanup } from "solid-js";
import measureInteractions from "~/common/measureInteractions";
import measureLoAF from "~/common/measureLoAF";

export default function WebVitalsMonitor() {
	createEffect(() => {
		// console.log('Recording Interaction to Next Paint (INP).');

		const observers = [
			measureInteractions(),
			measureLoAF(),
		];
		onCleanup(() => observers.forEach(observer => observer?.disconnect()));
	});

	return <></>;
}
