// sandbox/io23-demo/SolidJS/src/hooks/utils/useAwaitableTransition.tsx
import { Accessor, createEffect, createRenderEffect, useTransition } from "solid-js";

export default function useAwaitableTransition() : [Accessor<boolean>, (fn: () => void) => Promise<void>] {
	const [isPending, startTransition] = useTransition();
	let resolveRef: (((value?: any) => void) | undefined);
	let rejectRef: (((reason?: any) => void) | undefined);

	const startAwaitableTransition = async (callback: () => void): Promise<void> => {
		rejectRef?.();

		return new Promise((resolve, reject) => {
			resolveRef = resolve;
			rejectRef = reject;

			startTransition(() => {
				callback();
			});
		});
	};
	
	// TODO: Try render effect?
	createRenderEffect(() => {
		if (!isPending()) {
			resolveRef?.();

			resolveRef = undefined;
			rejectRef = undefined;
		}
	});

	return [isPending, startAwaitableTransition];
}

// sandbox/io23-demo/React/src/hooks/utils/useAwaitableTransition.ts
import { TransitionFunction, TransitionStartFunction, useCallback, useEffect, useRef, useTransition } from "react";

export default function useAwaitableTransition() : [boolean, TransitionStartFunction] {
	const [isPending, startTransition] = useTransition();
	const resolveRef = useRef<(value?: unknown) => void>();
	const rejectRef = useRef<(reason?: any) => void>();

	const wrappedStartTransition = useCallback(
		(callback: TransitionFunction) => {
			rejectRef.current?.();

			return new Promise((resolve, reject) => {
				resolveRef.current = resolve;
				rejectRef.current = reject;

				startTransition(() => {
					callback();
				});
			});
		}, [startTransition, rejectRef]);
	
	useEffect(() => {
		if (!isPending) {
			resolveRef.current?.();

			resolveRef.current = undefined;
			rejectRef.current = undefined;
		}
	}, [isPending]);

	return [isPending, wrappedStartTransition];
};
