// sandbox/io23-demo/SolidJS/src/hooks/useDebouncedEffect.tsx
import { Accessor, createEffect, onCleanup } from "solid-js";

// This is a very trivial version of this hook.
// There are several libraries that provide more robust versions.
export default function useDefferredEffect<T>(deps: Accessor<T>, callback: (val: T) => void, delay: number) {
	// TODO: perhaps using the promise based version of setTimeout and createResource() is better
	createEffect(() => {
		const val = deps();
		const timerid = setTimeout(() => callback(val), delay);
		onCleanup(() => {
			clearTimeout(timerid);
		});
	});
  };

// sandbox/io23-demo/React/src/hooks/utils/useDebouncedEffect.ts
import { DependencyList, EffectCallback, useEffect } from "react";

// This is a very trivial version of this hook.
// There are several libraries that provide more robust versions.
export default function useDebouncedEffect(callback: EffectCallback, deps: DependencyList, delay: number) {
	useEffect(() => {
		const timerid = setTimeout(callback, delay);
		return () => {
			clearTimeout(timerid);
		};
	}, [delay, callback, ...deps]);
}
