// sandbox/io23-demo/SolidJS/src/components/AutoCompleteAsync.tsx
'use client';

import createSearchTasks, { SearchResult, SearchTask } from "~/common/createSearchTasks";
import SailboatPreview from "./SailboatPreview";
import { Accessor, For, createResource } from 'solid-js';
import filterResultsAsync from "~/common/filterResultsAsync";
import { SailData } from "~/common/getSailData";
import Fuse from "fuse.js";

export default function AutoComplete({ searchTerm, sailData, abortSignal }: { searchTerm: Accessor<string>, sailData: SailData, abortSignal: Accessor<AbortSignal> }) {
	const [searchers] = createResource(() => createSearchTasks(Fuse, sailData));
	const [results] =  createResource(() => [searchTerm(), abortSignal()], ([searchTerm, abortSignal]) => filterResultsAsync(searchers()!, searchTerm as string, abortSignal as AbortSignal));
	const slicedResults = () => results()?.slice(0, 10);

	return (
		<>
			<div>Results ({results()?.length}):</div>
			<For each={slicedResults()}>{(result: SearchResult) =>
				<SailboatPreview result={result}></SailboatPreview>
			}</For>
		</>
	);
};

// sandbox/io23-demo/src/components/AutoCompleteAsync.tsx
'use client';

import useSailBoatData from "@/hooks/useSailboatData";
import useFilteredResults from "@/hooks/useFilteredResultsAsync";
import SailboatPreview from "./SailboatPreview";

export default function AutoComplete({ searchTerm, abortSignal }: { searchTerm: string, abortSignal: AbortSignal }) {
	const sailData = useSailBoatData();

	// This can be expensive!
	const results = useFilteredResults(sailData, searchTerm, abortSignal);

	if (results.length == 0) {
		return <></>;
	}

	return (
		<>
			<div>Results ({results.length}):</div>
			{ results.slice(0, 10).map((result: any) =>
				<SailboatPreview key={result.item.id} result={result}></SailboatPreview>
			)}
		</>
	);
};
