// sandbox/io23-demo/SolidJS/src/components/SearchBar.tsx
import { Accessor, JSX } from "solid-js";

export default function SearchBar({ searchTerm, onInput: onInput }: { searchTerm: Accessor<string>, onInput: JSX.EventHandler<HTMLInputElement, InputEvent> }) {
	return <>
		<form class="p-5 w-full max-w-sm text-2xl font-semibold" onSubmit={(e) => e.preventDefault()}>
			<div class="flex items-center border-b border-teal-500 py-2">
				<input onInput={onInput} value={searchTerm()} class="appearance-none bg-transparent border-none w-full mr-3 py-1 px-2 leading-tight focus:outline-none" type="text" placeholder="Search" aria-label="Full name"></input>
			</div>
		</form>
	</>;
}

// sandbox/io23-demo/src/components/SearchBar.tsx
export default function SearchBar({ searchTerm, onChange }: { searchTerm: string, onChange: any }) {
	return <>
		<form className="p-5 w-full max-w-sm text-2xl font-semibold" onSubmit={(e) => e.preventDefault()}>
			<div className="flex items-center border-b border-teal-500 py-2">
				<input onChange={onChange} value={searchTerm} className="appearance-none bg-transparent border-none w-full mr-3 py-1 px-2 leading-tight focus:outline-none" type="text" placeholder="Search" aria-label="Full name"></input>
			</div>
		</form>
	</>;
}
