// sandbox/io23-demo/SolidJS/src/routes/better.tsx

import { createResource, createSignal, Show, Suspense, startTransition } from 'solid-js';

import getSailData from '~/common/getSailData';
import useDebouncedEffect from '~/hooks/utils/useDebouncedEffect';
import SearchBar from '~/components/SearchBar';
import AutoCompleteSync from '~/components/AutoCompleteSync';

export default function SolidSearchBetter() {
	const [sailData] = createResource(getSailData);
	const [searchTerm, setSearchTerm] = createSignal("");
	const [autocompleteTerm, setAutocompleteTerm] = createSignal("");

	// Because we debounce the effect, we don't use the transition isPending
	const isPending = () => searchTerm() != autocompleteTerm();

	useDebouncedEffect(searchTerm, (searchTerm: string) => {
		startTransition(() => {
			setAutocompleteTerm(searchTerm);
		});
	}, 1000);

	const onInput = async (e: any) => {
		const searchTerm = e.target.value;
		setSearchTerm(searchTerm);
	};

	return (
		<Show when={!sailData.loading}>
			<SearchBar searchTerm={searchTerm} onInput={onInput}></SearchBar>

			<div class={isPending() ? "blur-sm" : ""}>
				<Suspense>
					<AutoCompleteSync searchTerm={autocompleteTerm} sailData={sailData()!}></AutoCompleteSync>
				</Suspense>
			</div>
		</Show>
	);
}

// sandbox/io23-demo/NextJS/src/pages/better.tsx
'use client';
import { ChangeEvent, Suspense, startTransition, use, useMemo, useState } from "react";

import getSailData from "@/common/getSailData";
import useDebouncedEffect from "../hooks/utils/useDebouncedEffect";
import SearchBar from "../components/SearchBar";
import AutoCompleteSync from "../components/AutoCompleteSync";

export default function ReactSearchBetter() {
	const sailData = use(useMemo(() => getSailData(), []));
	const [searchTerm, setSearchTerm] = useState("");
	const [autoCompleteTerm, setAutoCompleteTerm] = useState(searchTerm);

	// Because we debounce the effect, we don't use the transition isPending
	const isPending = searchTerm != autoCompleteTerm;

	useDebouncedEffect(() => {
		startTransition(() => {
			setAutoCompleteTerm(searchTerm);
		});
	}, [searchTerm, setAutoCompleteTerm], 1000);

	const onInput = (e: ChangeEvent<HTMLInputElement>) => {
		const searchTerm = e.target.value;
		setSearchTerm(searchTerm);
	};

	return (
		<>
			<SearchBar searchTerm={searchTerm} onInput={onInput}></SearchBar>

			<div className={isPending ? "blur-sm" : ""}>
				<Suspense>
					<AutoCompleteSync searchTerm={autoCompleteTerm} sailData={sailData!}></AutoCompleteSync>
				</Suspense>
			</div>
		</>
	)
}
